<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260708130913 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE companies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, website TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE offers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, kind VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, city VARCHAR(120) DEFAULT NULL, country VARCHAR(2) DEFAULT NULL, is_remote BOOLEAN NOT NULL, latitude INT DEFAULT NULL, longitude INT DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, starts_at DATE NOT NULL, ends_at DATE DEFAULT NULL, salary_min INT DEFAULT NULL, salary_max INT DEFAULT NULL, salary_currency VARCHAR(3) DEFAULT NULL, contract VARCHAR(10) NOT NULL, extracted_skills TEXT NOT NULL, external_url TEXT NOT NULL, is_duplicate BOOLEAN NOT NULL, views_count INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id_id INT NOT NULL, source_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DA46042738B53C32 ON offers (company_id_id)');
        $this->addSql('CREATE INDEX IDX_DA460427E64C4568 ON offers (source_id_id)');
        $this->addSql('CREATE TABLE offers_categories (offers_id INT NOT NULL, categories_id INT NOT NULL, PRIMARY KEY (offers_id, categories_id))');
        $this->addSql('CREATE INDEX IDX_C5A19C67A090B42E ON offers_categories (offers_id)');
        $this->addSql('CREATE INDEX IDX_C5A19C67A21214B7 ON offers_categories (categories_id)');
        $this->addSql('CREATE TABLE sources (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, base_url TEXT NOT NULL, fetch_method VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_favorites (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, offer_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E489ED119D86650F ON user_favorites (user_id_id)');
        $this->addSql('CREATE INDEX IDX_E489ED11FC69E3BE ON user_favorites (offer_id_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password_hash VARCHAR(255) NOT NULL, first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL, cv_text TEXT DEFAULT NULL, skills JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON users (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE offers ADD CONSTRAINT FK_DA46042738B53C32 FOREIGN KEY (company_id_id) REFERENCES companies (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE offers ADD CONSTRAINT FK_DA460427E64C4568 FOREIGN KEY (source_id_id) REFERENCES sources (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE offers_categories ADD CONSTRAINT FK_C5A19C67A090B42E FOREIGN KEY (offers_id) REFERENCES offers (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE offers_categories ADD CONSTRAINT FK_C5A19C67A21214B7 FOREIGN KEY (categories_id) REFERENCES categories (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_favorites ADD CONSTRAINT FK_E489ED119D86650F FOREIGN KEY (user_id_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_favorites ADD CONSTRAINT FK_E489ED11FC69E3BE FOREIGN KEY (offer_id_id) REFERENCES offers (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE offers DROP CONSTRAINT FK_DA46042738B53C32');
        $this->addSql('ALTER TABLE offers DROP CONSTRAINT FK_DA460427E64C4568');
        $this->addSql('ALTER TABLE offers_categories DROP CONSTRAINT FK_C5A19C67A090B42E');
        $this->addSql('ALTER TABLE offers_categories DROP CONSTRAINT FK_C5A19C67A21214B7');
        $this->addSql('ALTER TABLE user_favorites DROP CONSTRAINT FK_E489ED119D86650F');
        $this->addSql('ALTER TABLE user_favorites DROP CONSTRAINT FK_E489ED11FC69E3BE');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE companies');
        $this->addSql('DROP TABLE offers');
        $this->addSql('DROP TABLE offers_categories');
        $this->addSql('DROP TABLE sources');
        $this->addSql('DROP TABLE user_favorites');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
